name: pokede
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/region/region-kanto.png
    - assets/region/region-johto.png
    - assets/region/region-hoenn.png
    - assets/region/region-sinnoh.png
    - assets/region/region-unys.png